FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime
USER root
ENV TZ=Asia/Dubai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update -y && \
    apt-get install -y \
    gcc\
    vim \
    htop \
    git \
    less \
    tree \
    tmux \
    zip\
    unzip\
    openssh-server \
    libgl1-mesa-glx \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/li \
    apt install build-essentia

RUN pip install flake8 yapf lmdb pillow\
    natsort matplotlib \
    wandb jupyter pandas fire tqdm scipy \
     deepspeed  pesq\
    cython numpy 