FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel 
# FROM pytorch/pytorch:1.9.1-cuda11.1-cudnn8-runtime
USER root
ENV TZ=Asia/Dubai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update -y && \
    apt-get install -y \
    gcc\
    vim \
    htop \
    git \
    less \
    tree \
    tmux \
    zip\
    unzip\
    libsndfile1\
    openssh-server \
    libgl1-mesa-glx \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/li \
    apt install build-essentia \
    && git config --global user.name "Jay Wu"\
    && git config --global user.email "e14051350@gs.ncku.edu.tw"

RUN pip install flake8 yapf lmdb pillow\
    natsort matplotlib \
    wandb jupyter pandas fire tqdm scipy \
     deepspeed  pesq\
    cython numpy soundfile

RUN conda install -c pytorch torchaudio -y